const SERVICE_HOST = '0.0.0.0'
const USER_SERVICE_URI = `${SERVICE_HOST}:50051`
const RESERVATION_SERVICE_URI = `${SERVICE_HOST}:50052`
const ROOM_SERVICE_URI = `${SERVICE_HOST}:50053`

module.exports = {USER_SERVICE_URI, RESERVATION_SERVICE_URI, ROOM_SERVICE_URI}