http:
  port: 8080

apiEndpoints:
  user:
    methods: 'GET,POST,PUT,DELETE'
    host: localhost
    paths: "/api/user/*"

serviceEndpoints:
  userService:
    url: "http://localhost:8081"
  
policies:
  - proxy

pipelines:
  user:
    apiEndpoints:
      - user
    policies:
      - proxy:
          action:
            serviceEndpoint: userService
            changeOrigin: true
